In [10]:
import pandas as pd
import zipfile
from google.colab import files

# Upload the ZIP file
uploaded = files.upload()

# Get ZIP filename
zip_file = list(uploaded.keys())[0]

# Extract the ZIP file
with zipfile.ZipFile(zip_file, 'r') as z:
    z.extractall("aqi_data")

    # Load the dataset
    df = pd.read_csv("aqi_data/INDIA_AQI_COMPLETE_20251126.csv")

    # Dataset Representation
    print("Dataset Shape:", df.shape)

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    display(df.dtypes)

    print("\nMissing Values:")
    display(df.isnull().sum())

    print("\nDuplicate Rows:", df.duplicated().sum())

    print("\nStatistical Summary:")
    display(df.describe())

Saving archive (1).zip to archive (1) (2).zip
Dataset Shape: (842160, 71)

First 5 Rows:

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,...,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,2022-08-05 00:00:00,2022,8,5,0,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,2022-08-05 01:00:00,2022,8,5,1,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,2022-08-05 02:00:00,2022,8,5,2,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,2022-08-05 03:00:00,2022,8,5,3,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,2022-08-05 04:00:00,2022,8,5,4,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

Column Names:
['City', 'State', 'Latitude', 'Longitude', 'Datetime', 'Year', 'Month', 'Day', 'Hour', 'Day_of_Week', 'Day_Name', 'Week_of_Year', 'Is_Weekend', 'Quarter', 'Season', 'Time_of_Day', 'Temp_2m_C', 'Temp_80m_C', 'Temp_120m_C', 'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C', 'Humidity_Category', 'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh', 'Wind_Speed_120m_kmh', 'Wind_Dir_10m', 'Wind_Gusts_kmh', 'Wind_Category', 'Wind_Stagnation', 'Precipitation_mm', 'Rain_mm', 'Is_Raining', 'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2', 'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent', 'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime', 'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD', 'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3', 'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category', 'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C', 'Festival_Period', 'Crop_Burning_Season']

Data Types:

City                     object
State                    object
Latitude                float64
Longitude               float64
Datetime                 object
                         ...
PM25_Category_India      object
Temp_Inversion            int64
Inversion_Strength_C    float64
Festival_Period           int64
Crop_Burning_Season       int64
Length: 71, dtype: object

Missing Values:

City                         0
State                        0
Latitude                     0
Longitude                    0
Datetime                     0
                         ...
PM25_Category_India          2
Temp_Inversion               0
Inversion_Strength_C    842160
Festival_Period              0
Crop_Burning_Season          0
Length: 71, dtype: int64

Duplicate Rows: 0

Statistical Summary:

,Latitude,Longitude,Year,Month,Day,Hour,Day_of_Week,Week_of_Year,Is_Weekend,Quarter,...,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
count,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,...,842158.000000,842087.000000,842160.000000,842015.000000,842015.000000,842015.000000,842160.0,0.0,842160.000000,842160.000000
mean,23.129041,82.769207,2023.724793,6.801653,15.736364,11.500000,3.000000,27.767769,0.285950,2.601653,...,7.961582,45.180426,4.355863,62.815243,58.034527,48.424171,0.0,NaN,0.105785,0.198347
std,5.543478,6.937205,0.995593,3.411504,8.767003,6.922191,2.000827,14.848660,0.451866,1.112661,...,10.379884,35.429652,3.892871,39.511570,31.666455,38.903157,0.0,NaN,0.307563,0.398755
min,8.524100,72.571400,2022.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,5.000000,1.000000,1.000000,0.0,NaN,0.000000,0.000000
25%,20.296100,77.173400,2023.000000,4.000000,8.000000,5.750000,1.000000,15.000000,0.000000,2.000000,...,2.000000,24.000000,2.000000,36.000000,31.000000,23.000000,0.0,NaN,0.000000,0.000000
50%,23.831500,80.946200,2024.000000,7.000000,16.000000,11.500000,3.000000,29.000000,0.000000,3.000000,...,4.000000,35.000000,3.000000,62.000000,61.000000,40.000000,0.0,NaN,0.000000,0.000000
75%,26.912400,88.606500,2025.000000,10.000000,23.000000,17.250000,5.000000,41.000000,1.000000,4.000000,...,10.000000,49.000000,5.000000,77.000000,75.000000,67.000000,0.0,NaN,0.000000,0.000000
max,31.104800,94.108600,2025.000000,12.000000,31.000000,23.000000,6.000000,52.000000,1.000000,4.000000,...,115.000000,369.000000,126.000000,1179.000000,301.000000,1179.000000,0.0,NaN,1.000000,1.000000